### ISSUE TITLE
Large file support on 32 bit systems

### ISSUE THREAD

**Issue by rdmark** [bfranske/hfdisk#2]
On 32 bit systems hfdisk is only able to operate on image files up to 2GiB of size (signed 32 bit int).

```
$ fallocate -l 3GB 3gig
$ hfdisk 3gig
hfdisk: can't open file '3gig'  (Value too large for defined data type)
```

The limit seems to be with open() from C libs, used in the open_device() function in io.c

**Comment by bfranske** [comment]
FYI I am not maintaining this, just mirroring it from [www.codesrc.com/gitweb/index.cgi?p=hfdisk.git](http://www.codesrc.com/gitweb/index.cgi?p=hfdisk.git) because I wanted to preserve it somewhere in case that site went down and make it easier to find. The last person to modify the code was michael@codesrc.com in 2013. You can either submit a patch to him or fork it yourself and host it somewhere (PiSCSI repo?) where it can be properly maintained.

**Comment by rdmark** [comment]
FWIW I contacted Michael a few months ago about the compiler warning patches but he wasn't interested.

In fact, the codesrc.com git repo `git://www.codesrc.com/git/hfdisk.git` has been down for at least a year (although the web frontend is still alive) so it was a good thing that you forked it when you did.

**Comment by bfranske** [comment]
Thanks for the update. I don't have the bandwidth to properly monitor patches and issues on this so if you want to host it elsewhere please do and I will replace this repo with a link to yours. :)

**Comment by rdmark** [comment]
Fair enough. Thanks for setting the right expectations. The PiSCSI project might not be the best home for hfdisk since they're only tangentially related. If you prefer, I believe github allows you to designate my fork as the "main" one instead of yours.
